pivotal-container-service_pks_tls_certificate: ((pks-tls-cert.certificate))
pivotal-container-service_pks_tls_privatekey: ((pks-tls-cert.private_key))
cloud_provider_azure_subscription_id: ((subscription_id))
cloud_provider_azure_tenant_id: ((tenant_id))
