---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "cf*.pivotal"
pivnet-product-slug: "elastic-runtime"
product-version: "2.9.1"

azure-storage-account: telmoreprodandstemcell
azure-storage-key: ((azure-storage-key))
blobstore-bucket: productstorage