---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "*.pivotal"
pivnet-product-slug: "elastic-runtime"
product-version: "2.6.20"

azure-storage-account: telmoreprodandstemcell
azure-storage-key: ((azure-storage-key))
blobstore-bucket: productstorage