---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "*-azure-*"
pivnet-product-slug: "stemcells-ubuntu-xenial"
product-version: "456.112"

azure-storage-account: telmoreprodandstemcell
azure-storage-key: ((azure-storage-key))
blobstore-bucket: productstorage