---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "*.pivotal"
pivnet-product-slug: "p-healthwatch"
product-version: "1.8.1"

azure-storage-account: telmoreprodandstemcell
azure-storage-key: ((azure-storage-key))
blobstore-bucket: productstorage