---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "*.pivotal"
pivnet-product-slug: "pivotal-container-service"
product-version: "1.7.0"

azure-storage-account: telmoreprodandstemcell
azure-storage-key: ((azure-storage-key))
blobstore-bucket: productstorage