resources:
- name: lock
  type: pool
  source:
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    branch: master
    username: ((github_username))
    password: ((github_token))
    pool: locks/((lock_pool_name))
    retry_delay: 1m

jobs:
- name: force-unlock
  serial: true
  plan:
  - get: lock
  - put: lock
    params:
      release: lock

- name: lock-job-a
  serial: true
  plan:
  - aggregate:
    - get: lock
    - put: lock
      params: {acquire: true}

- name: job-a
  public: true
  plan:
    - get: lock
      trigger: true
      passed:
      - "lock-job-a"
    - task: PrintItOut
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        run:
          path: echo
          args: ["Hello, Job A!"]

# - name: unlock-job-a
#   serial: true
#   plan:
#   - get: lock
#     trigger: true
#     passed:
#     - "job-a"
#   - put: lock
#     params:
#       release: lock

- name: lock-job-b
  serial: true
  plan:
  - aggregate:
    - get: lock
    - put: lock
      params: {acquire: true}

- name: job-b
  public: true
  plan:
    - get: lock
      trigger: true
      passed:
      - "lock-job-b"
    - task: PrintItOut
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        run:
          path: echo
          args: ["Hello, Job B!"]

- name: unlock-job-b
  serial: true
  plan:
  - get: lock
    trigger: true
    passed:
    - "job-b"
  - put: lock
    params:
      release: lock
      