resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation

- name: configuration
  type: git
  source:
    branch: master
    password: ((github_token))
    uri: https://github.com/tonyelmore/telmore-platform-automation.git
    username: ((github_username))
    paths:
    - "environments/((iaas))/((foundation))/config"

- name: pivnet-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: pivnet-cli
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: jq
  type: github-release
  source:
    user: stedolan
    repository: jq
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit

jobs:
- name: pull-products-from-pivnet
  plan:
  - aggregate:
    - get: configuration
      trigger: true
      # passed: ["validate-director-configuration"]
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs: ["*image*"]
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        unpack: true
        globs: ["*tasks*"]
    # - get: docker-image
    - get: pivnet-cli
      params:
        globs:
        - "*linux-amd64*"
    - get: jq
      params:
        globs:
        - "*linux64*"

  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params: &credhub_interpolate_params
      CREDHUB_SERVER: https://ci.concourse.my3votes.com:8844
      CREDHUB_CA_CERT: ((concourse_credhub_ca.certificate))
      CREDHUB_CLIENT: ((concourse_credhub_client_username))
      CREDHUB_SECRET: ((concourse_credhub_client_secret))
      PREFIX: '/concourse/((team))'
      INTERPOLATION_PATHS: "environments/((iaas))/((foundation))/config/secrets"
    input_mapping:
      files: configuration

  # - task: display-cred
  #   config:
  #     run:
  #       path: bash
  #       args: [-c, "echo Hello, ((provided-by-credhub))"]

  - task: download-upload-product
    image: platform-automation-image
    file: configuration/ci/tasks-proposed/download-upload-product.yml
    input_mapping:
      config: configuration
      secrets: interpolated-files
    params:
     # PRODUCT_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf.yml
     # STEMCELL_CONFIG_FILE: environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml
      AZURE_SECRETS_PATH: environments/((iaas))/((foundation))/config/secrets/azure.yml
      PIVNET_SECRETS_PATH: environments/((iaas))/((foundation))/config/secrets/pivnet.yml
      CONFIG_FILES: |
        environments/((iaas))/((foundation))/config/versions/cf.yml
        environments/((iaas))/((foundation))/config/versions/cf-stemcell.yml
        environments/((iaas))/((foundation))/config/versions/p-healthwatch.yml
        environments/((iaas))/((foundation))/config/versions/p-healthwatch-stemcell.yml
        environments/((iaas))/((foundation))/config/versions/pivotal-container-service.yml
        environments/((iaas))/((foundation))/config/versions/pivotal-container-service-stemcell.yml
      VARS_FILES: |
        secrets/environments/((iaas))/((foundation))/config/secrets/pivnet.yml
        secrets/environments/((iaas))/((foundation))/config/secrets/azure.yml
