cloud_controller_apps_domain: apps.sbx.my3votes.com
cloud_controller_system_domain: sys.sbx.my3votes.com
singleton_availability_zone: zone-1
az2_name: zone-2
az3_name: zone-3

router_elb_names: ["sbx-web-lb"]
router_additional_vm_extensions: ["sbx-platform-vms-sg"]
diego_brain_additional_vm_extensions: ["sbx-diego-ssh-lb"]
diego_brain_elb_names: ["sbx-platform-vms-sg"]
tcp_router_additional_vm_extensions: ["sbx-tcp-lb"]
tcp_router_elb_names: ["sbx-platform-vms-sg"]