cloud_controller_apps_domain: apps.sbx.my3votes.com
cloud_controller_system_domain: sys.sbx.my3votes.com
singleton_availability_zone: zone-1
az2_name: zone-2
az3_name: zone-3

router_elb_names: ["sbx-web-lb"]
